// This is the first Exmaple of IF Statements works the first method.
class conditional {
 public static void main(String[] args) {
  int x = 10;

  if (x > 4) {
   System.out.println("x is greater than 4");
  }
 }
}

// IF else statement 2nd exmaple this is for if 

class conditional {
    public static void main(String[] args) {
        int x = 1;
        
        if (x > 4) {
            System.out.println("x is greater than 4");
        } 
        else {
            System.out.println("x is less than 4");
        }
    }
}

// IF else IF statement for if the 1st and 2nd ones.

class conditional {
    public static void main(String[] args) {
        int x = 4;

        if (x > 4) {
            System.out.println("x is greater than 4");
        }
        else if (x == 4) {
            System.out.println("x is equal to 4");
        } 
        else {
            System.out.println("x is less than 4");
        }
    }
}
